version: '3'

services:
  bookings:
    image: allisonc07/bookings:1.5
    depends_on:
      - 'database'
    ports:
      - '3002:3002'

  database:
    image: mysql:5.7
    ports:
      - '3306:3306'
    environment:
      MYSQL_ROOT_PASSWORD: '1234'
    volumes:
      - ./dump.sql:/docker-entrypoint-initdb.d/dump.sql