# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      - image: circleci/node:8.11.3
      
      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/mongo:3.4.4
      - image: circleci/mysql:5.7.22

    working_directory: ~/Dev/bookings

    steps:
      - checkout
      - run: sudo apt install mysql-client
      - run:
          name: update-npm
          command: 'sudo npm install -g npm@6.2.0'
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: install-npm-wee
          command: npm install
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - ./node_modules
      - run:
          name: seed
          command: mysql  -h 127.0.0.1 --local-infile -u root < schema.sql
      - run:
          name: test
          command: npm test
